Algoritmo "crescente"
var

   X, Y : inteiro
   
inicio

      escreval("Digite dois numeros: ")
      leia(X)
      leia(Y)
      
      enquanto X <> Y faca

               se X < Y entao
                  escreval("Crescente")
               senao
                    escreval("Decrescente")
               fimse
               
               escreval("Digite outros dois numeros: ")
               leia(X)
               leia(Y)
       fimenquanto
               

Fimalgoritmo